
// init_data.js — Generado automáticamente por generar_datos.py
(function() {
    const data = {
    "usuarios": [
        {
            "nombre": "Valeria",
            "apellido": "Vargas",
            "correo": "valeria1@example.com",
            "password": "703647",
            "telefono": "939862820",
            "descripcion": "Usuario Valeria Vargas interesado en oportunidades inclusivas.",
            "discapacidad": "Fisica",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Raúl",
            "apellido": "López",
            "correo": "raúl2@example.com",
            "password": "284873",
            "telefono": "965847289",
            "descripcion": "Usuario Raúl López interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Valeria",
            "apellido": "Fernández",
            "correo": "valeria3@example.com",
            "password": "554980",
            "telefono": "988257134",
            "descripcion": "Usuario Valeria Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Gabriel",
            "apellido": "Ruiz",
            "correo": "gabriel4@example.com",
            "password": "209583",
            "telefono": "938070678",
            "descripcion": "Usuario Gabriel Ruiz interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Miguel",
            "apellido": "Castillo",
            "correo": "miguel5@example.com",
            "password": "400531",
            "telefono": "975359071",
            "descripcion": "Usuario Miguel Castillo interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Miguel",
            "apellido": "García",
            "correo": "miguel6@example.com",
            "password": "808022",
            "telefono": "964822905",
            "descripcion": "Usuario Miguel García interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Valeria",
            "apellido": "Pérez",
            "correo": "valeria7@example.com",
            "password": "130156",
            "telefono": "930106158",
            "descripcion": "Usuario Valeria Pérez interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Raúl",
            "apellido": "Cruz",
            "correo": "raúl8@example.com",
            "password": "259071",
            "telefono": "947740451",
            "descripcion": "Usuario Raúl Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Raúl",
            "apellido": "Cruz",
            "correo": "raúl9@example.com",
            "password": "363130",
            "telefono": "978067092",
            "descripcion": "Usuario Raúl Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Camila",
            "apellido": "Fernández",
            "correo": "camila10@example.com",
            "password": "872007",
            "telefono": "910592559",
            "descripcion": "Usuario Camila Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Héctor",
            "apellido": "Fernández",
            "correo": "héctor11@example.com",
            "password": "307671",
            "telefono": "977061301",
            "descripcion": "Usuario Héctor Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Paola",
            "apellido": "Castillo",
            "correo": "paola12@example.com",
            "password": "513935",
            "telefono": "940814882",
            "descripcion": "Usuario Paola Castillo interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Elena",
            "apellido": "Torres",
            "correo": "elena13@example.com",
            "password": "327888",
            "telefono": "968617362",
            "descripcion": "Usuario Elena Torres interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Gabriel",
            "apellido": "Ramírez",
            "correo": "gabriel14@example.com",
            "password": "547747",
            "telefono": "963825658",
            "descripcion": "Usuario Gabriel Ramírez interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Paola",
            "apellido": "Ruiz",
            "correo": "paola15@example.com",
            "password": "976028",
            "telefono": "978769461",
            "descripcion": "Usuario Paola Ruiz interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Juan",
            "apellido": "Cruz",
            "correo": "juan16@example.com",
            "password": "148800",
            "telefono": "971762682",
            "descripcion": "Usuario Juan Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Elena",
            "apellido": "López",
            "correo": "elena17@example.com",
            "password": "649544",
            "telefono": "937590891",
            "descripcion": "Usuario Elena López interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Elena",
            "apellido": "Ruiz",
            "correo": "elena18@example.com",
            "password": "575818",
            "telefono": "929036301",
            "descripcion": "Usuario Elena Ruiz interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Valeria",
            "apellido": "García",
            "correo": "valeria19@example.com",
            "password": "457472",
            "telefono": "963031713",
            "descripcion": "Usuario Valeria García interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Rosa",
            "apellido": "Fernández",
            "correo": "rosa20@example.com",
            "password": "310419",
            "telefono": "944826212",
            "descripcion": "Usuario Rosa Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Fisica",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Jorge",
            "apellido": "Ruiz",
            "correo": "jorge21@example.com",
            "password": "837269",
            "telefono": "993148031",
            "descripcion": "Usuario Jorge Ruiz interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Camila",
            "apellido": "Ramírez",
            "correo": "camila22@example.com",
            "password": "582330",
            "telefono": "940495124",
            "descripcion": "Usuario Camila Ramírez interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Raúl",
            "apellido": "García",
            "correo": "raúl23@example.com",
            "password": "685269",
            "telefono": "980586175",
            "descripcion": "Usuario Raúl García interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Gabriel",
            "apellido": "Pérez",
            "correo": "gabriel24@example.com",
            "password": "621688",
            "telefono": "937732367",
            "descripcion": "Usuario Gabriel Pérez interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Sofía",
            "apellido": "Castillo",
            "correo": "sofía25@example.com",
            "password": "621586",
            "telefono": "966931923",
            "descripcion": "Usuario Sofía Castillo interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Raúl",
            "apellido": "Ruiz",
            "correo": "raúl26@example.com",
            "password": "444870",
            "telefono": "968367458",
            "descripcion": "Usuario Raúl Ruiz interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Paola",
            "apellido": "Castillo",
            "correo": "paola27@example.com",
            "password": "177710",
            "telefono": "976600768",
            "descripcion": "Usuario Paola Castillo interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Sofía",
            "apellido": "López",
            "correo": "sofía28@example.com",
            "password": "744750",
            "telefono": "912389117",
            "descripcion": "Usuario Sofía López interesado en oportunidades inclusivas.",
            "discapacidad": "Fisica",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Andrés",
            "apellido": "Cruz",
            "correo": "andrés29@example.com",
            "password": "418093",
            "telefono": "962947511",
            "descripcion": "Usuario Andrés Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Luis",
            "apellido": "Vargas",
            "correo": "luis30@example.com",
            "password": "802173",
            "telefono": "958205966",
            "descripcion": "Usuario Luis Vargas interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Andrés",
            "apellido": "Castillo",
            "correo": "andrés31@example.com",
            "password": "893593",
            "telefono": "933133597",
            "descripcion": "Usuario Andrés Castillo interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Camila",
            "apellido": "Castillo",
            "correo": "camila32@example.com",
            "password": "182055",
            "telefono": "975854098",
            "descripcion": "Usuario Camila Castillo interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "María",
            "apellido": "Ramírez",
            "correo": "maría33@example.com",
            "password": "772768",
            "telefono": "964504085",
            "descripcion": "Usuario María Ramírez interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Pedro",
            "apellido": "Fernández",
            "correo": "pedro34@example.com",
            "password": "613008",
            "telefono": "971975252",
            "descripcion": "Usuario Pedro Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Rosa",
            "apellido": "Fernández",
            "correo": "rosa35@example.com",
            "password": "819017",
            "telefono": "956014912",
            "descripcion": "Usuario Rosa Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Fisica",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Gabriel",
            "apellido": "Cruz",
            "correo": "gabriel36@example.com",
            "password": "906425",
            "telefono": "935411238",
            "descripcion": "Usuario Gabriel Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Rosa",
            "apellido": "Pérez",
            "correo": "rosa37@example.com",
            "password": "771932",
            "telefono": "916370249",
            "descripcion": "Usuario Rosa Pérez interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Claudia",
            "apellido": "Ramírez",
            "correo": "claudia38@example.com",
            "password": "720765",
            "telefono": "921997594",
            "descripcion": "Usuario Claudia Ramírez interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Camila",
            "apellido": "Torres",
            "correo": "camila39@example.com",
            "password": "623680",
            "telefono": "947195486",
            "descripcion": "Usuario Camila Torres interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "María",
            "apellido": "Torres",
            "correo": "maría40@example.com",
            "password": "187389",
            "telefono": "979255254",
            "descripcion": "Usuario María Torres interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Valeria",
            "apellido": "Ramírez",
            "correo": "valeria41@example.com",
            "password": "666550",
            "telefono": "929249733",
            "descripcion": "Usuario Valeria Ramírez interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Sofía",
            "apellido": "García",
            "correo": "sofía42@example.com",
            "password": "149831",
            "telefono": "920672527",
            "descripcion": "Usuario Sofía García interesado en oportunidades inclusivas.",
            "discapacidad": "Psicosocial",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Miguel",
            "apellido": "Fernández",
            "correo": "miguel43@example.com",
            "password": "482900",
            "telefono": "930602445",
            "descripcion": "Usuario Miguel Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Claudia",
            "apellido": "Cruz",
            "correo": "claudia44@example.com",
            "password": "134023",
            "telefono": "970412153",
            "descripcion": "Usuario Claudia Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Rosa",
            "apellido": "Cruz",
            "correo": "rosa45@example.com",
            "password": "884352",
            "telefono": "938148405",
            "descripcion": "Usuario Rosa Cruz interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Jorge",
            "apellido": "López",
            "correo": "jorge46@example.com",
            "password": "855175",
            "telefono": "980124457",
            "descripcion": "Usuario Jorge López interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Héctor",
            "apellido": "Vargas",
            "correo": "héctor47@example.com",
            "password": "272945",
            "telefono": "964039109",
            "descripcion": "Usuario Héctor Vargas interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Paola",
            "apellido": "Torres",
            "correo": "paola48@example.com",
            "password": "523031",
            "telefono": "995335406",
            "descripcion": "Usuario Paola Torres interesado en oportunidades inclusivas.",
            "discapacidad": "Intelectual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Carlos",
            "apellido": "Ramírez",
            "correo": "carlos49@example.com",
            "password": "984906",
            "telefono": "925054599",
            "descripcion": "Usuario Carlos Ramírez interesado en oportunidades inclusivas.",
            "discapacidad": "Auditiva",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        },
        {
            "nombre": "Camila",
            "apellido": "Fernández",
            "correo": "camila50@example.com",
            "password": "760554",
            "telefono": "914468694",
            "descripcion": "Usuario Camila Fernández interesado en oportunidades inclusivas.",
            "discapacidad": "Visual",
            "fechaRegistro": "12/11/2025",
            "rol": "usuario"
        }
    ],
    "empresas": [
        {
            "nombre": "InclusiveLab #1",
            "ruc": "2018612938",
            "correo": "contacto1@inclusivelab.com",
            "telefono": "989485452",
            "direccion": "Avenida Principal 896, Arequipa",
            "descripcion": "Empresa InclusiveLab comprometida con la inclusión laboral.",
            "representante": "Paola Torres",
            "fechaRegistro": "12/11/2025",
            "estado": "Verificada"
        },
        {
            "nombre": "Cloudify #2",
            "ruc": "2068821488",
            "correo": "contacto2@cloudify.com",
            "telefono": "965662618",
            "direccion": "Avenida Principal 837, Lima",
            "descripcion": "Empresa Cloudify comprometida con la inclusión laboral.",
            "representante": "Pedro Torres",
            "fechaRegistro": "12/11/2025",
            "estado": "Verificada"
        },
        {
            "nombre": "Cloudify #3",
            "ruc": "2078655745",
            "correo": "contacto3@cloudify.com",
            "telefono": "985638936",
            "direccion": "Avenida Principal 940, Piura",
            "descripcion": "Empresa Cloudify comprometida con la inclusión laboral.",
            "representante": "Miguel Castillo",
            "fechaRegistro": "12/11/2025",
            "estado": "Verificada"
        },
        {
            "nombre": "PixelArt Studio #4",
            "ruc": "2068964077",
            "correo": "contacto4@pixelartstudio.com",
            "telefono": "928935674",
            "direccion": "Avenida Principal 516, Trujillo",
            "descripcion": "Empresa PixelArt Studio comprometida con la inclusión laboral.",
            "representante": "Pedro López",
            "fechaRegistro": "12/11/2025",
            "estado": "Verificada"
        },
        {
            "nombre": "EcoMarket #5",
            "ruc": "2093211833",
            "correo": "contacto5@ecomarket.com",
            "telefono": "992684296",
            "direccion": "Avenida Principal 308, Trujillo",
            "descripcion": "Empresa EcoMarket comprometida con la inclusión laboral.",
            "representante": "Paola Ruiz",
            "fechaRegistro": "12/11/2025",
            "estado": "Verificada"
        }
    ],
    "ofertas": [
        {
            "id": 1,
            "titulo": "Community Manager",
            "empresa": "Cloudify #3",
            "categoria": "Operaciones",
            "descripcion": "Puesto de Community Manager accesible para personas con discapacidad Auditiva.",
            "ciudad": "Cusco",
            "modalidad": "Híbrido",
            "discapacidad": "Auditiva",
            "estado": "Activa",
            "fecha": "2025-10-09"
        },
        {
            "id": 2,
            "titulo": "Gestor de Ventas",
            "empresa": "Cloudify #3",
            "categoria": "Tecnología",
            "descripcion": "Puesto de Gestor de Ventas accesible para personas con discapacidad Psicosocial.",
            "ciudad": "Piura",
            "modalidad": "Presencial",
            "discapacidad": "Psicosocial",
            "estado": "Activa",
            "fecha": "2025-04-14"
        },
        {
            "id": 3,
            "titulo": "Redactor de Contenido",
            "empresa": "EcoMarket #5",
            "categoria": "Marketing",
            "descripcion": "Puesto de Redactor de Contenido accesible para personas con discapacidad Fisica.",
            "ciudad": "Cusco",
            "modalidad": "Presencial",
            "discapacidad": "Fisica",
            "estado": "Activa",
            "fecha": "2025-06-25"
        },
        {
            "id": 4,
            "titulo": "Tester QA",
            "empresa": "Cloudify #2",
            "categoria": "Diseño",
            "descripcion": "Puesto de Tester QA accesible para personas con discapacidad Psicosocial.",
            "ciudad": "Piura",
            "modalidad": "Remoto",
            "discapacidad": "Psicosocial",
            "estado": "Activa",
            "fecha": "2025-05-28"
        },
        {
            "id": 5,
            "titulo": "Diseñador UX/UI",
            "empresa": "PixelArt Studio #4",
            "categoria": "Administración",
            "descripcion": "Puesto de Diseñador UX/UI accesible para personas con discapacidad Visual.",
            "ciudad": "Piura",
            "modalidad": "Presencial",
            "discapacidad": "Visual",
            "estado": "Activa",
            "fecha": "2025-01-22"
        },
        {
            "id": 6,
            "titulo": "Gestor de Ventas",
            "empresa": "PixelArt Studio #4",
            "categoria": "Tecnología",
            "descripcion": "Puesto de Gestor de Ventas accesible para personas con discapacidad Fisica.",
            "ciudad": "Cusco",
            "modalidad": "Remoto",
            "discapacidad": "Fisica",
            "estado": "Activa",
            "fecha": "2025-07-19"
        },
        {
            "id": 7,
            "titulo": "Community Manager",
            "empresa": "EcoMarket #5",
            "categoria": "Administración",
            "descripcion": "Puesto de Community Manager accesible para personas con discapacidad Visual.",
            "ciudad": "Trujillo",
            "modalidad": "Híbrido",
            "discapacidad": "Visual",
            "estado": "Activa",
            "fecha": "2025-08-21"
        },
        {
            "id": 8,
            "titulo": "Soporte Técnico",
            "empresa": "Cloudify #2",
            "categoria": "Administración",
            "descripcion": "Puesto de Soporte Técnico accesible para personas con discapacidad Psicosocial.",
            "ciudad": "Arequipa",
            "modalidad": "Híbrido",
            "discapacidad": "Psicosocial",
            "estado": "Activa",
            "fecha": "2025-11-06"
        },
        {
            "id": 9,
            "titulo": "Soporte Técnico",
            "empresa": "EcoMarket #5",
            "categoria": "Marketing",
            "descripcion": "Puesto de Soporte Técnico accesible para personas con discapacidad Auditiva.",
            "ciudad": "Arequipa",
            "modalidad": "Presencial",
            "discapacidad": "Auditiva",
            "estado": "Activa",
            "fecha": "2025-11-22"
        },
        {
            "id": 10,
            "titulo": "Community Manager",
            "empresa": "Cloudify #2",
            "categoria": "Contabilidad",
            "descripcion": "Puesto de Community Manager accesible para personas con discapacidad Fisica.",
            "ciudad": "Cusco",
            "modalidad": "Híbrido",
            "discapacidad": "Fisica",
            "estado": "Activa",
            "fecha": "2025-01-23"
        },
        {
            "id": 11,
            "titulo": "Soporte Técnico",
            "empresa": "Cloudify #3",
            "categoria": "Operaciones",
            "descripcion": "Puesto de Soporte Técnico accesible para personas con discapacidad Psicosocial.",
            "ciudad": "Lima",
            "modalidad": "Presencial",
            "discapacidad": "Psicosocial",
            "estado": "Activa",
            "fecha": "2025-12-08"
        },
        {
            "id": 12,
            "titulo": "Asistente Contable",
            "empresa": "Cloudify #2",
            "categoria": "Diseño",
            "descripcion": "Puesto de Asistente Contable accesible para personas con discapacidad Intelectual.",
            "ciudad": "Lima",
            "modalidad": "Remoto",
            "discapacidad": "Intelectual",
            "estado": "Activa",
            "fecha": "2025-04-04"
        },
        {
            "id": 13,
            "titulo": "Redactor de Contenido",
            "empresa": "Cloudify #3",
            "categoria": "Operaciones",
            "descripcion": "Puesto de Redactor de Contenido accesible para personas con discapacidad Visual.",
            "ciudad": "Lima",
            "modalidad": "Presencial",
            "discapacidad": "Visual",
            "estado": "Activa",
            "fecha": "2025-12-20"
        },
        {
            "id": 14,
            "titulo": "Diseñador UX/UI",
            "empresa": "EcoMarket #5",
            "categoria": "Diseño",
            "descripcion": "Puesto de Diseñador UX/UI accesible para personas con discapacidad Fisica.",
            "ciudad": "Lima",
            "modalidad": "Presencial",
            "discapacidad": "Fisica",
            "estado": "Activa",
            "fecha": "2025-02-02"
        },
        {
            "id": 15,
            "titulo": "Redactor de Contenido",
            "empresa": "PixelArt Studio #4",
            "categoria": "Diseño",
            "descripcion": "Puesto de Redactor de Contenido accesible para personas con discapacidad Psicosocial.",
            "ciudad": "Cusco",
            "modalidad": "Híbrido",
            "discapacidad": "Psicosocial",
            "estado": "Activa",
            "fecha": "2025-09-16"
        },
        {
            "id": 16,
            "titulo": "Community Manager",
            "empresa": "PixelArt Studio #4",
            "categoria": "Contabilidad",
            "descripcion": "Puesto de Community Manager accesible para personas con discapacidad Intelectual.",
            "ciudad": "Lima",
            "modalidad": "Presencial",
            "discapacidad": "Intelectual",
            "estado": "Activa",
            "fecha": "2025-02-20"
        },
        {
            "id": 17,
            "titulo": "Asistente Contable",
            "empresa": "EcoMarket #5",
            "categoria": "Administración",
            "descripcion": "Puesto de Asistente Contable accesible para personas con discapacidad Psicosocial.",
            "ciudad": "Trujillo",
            "modalidad": "Remoto",
            "discapacidad": "Psicosocial",
            "estado": "Activa",
            "fecha": "2025-02-22"
        },
        {
            "id": 18,
            "titulo": "Soporte Técnico",
            "empresa": "Cloudify #2",
            "categoria": "Marketing",
            "descripcion": "Puesto de Soporte Técnico accesible para personas con discapacidad Intelectual.",
            "ciudad": "Lima",
            "modalidad": "Remoto",
            "discapacidad": "Intelectual",
            "estado": "Activa",
            "fecha": "2025-07-01"
        },
        {
            "id": 19,
            "titulo": "Desarrollador Backend",
            "empresa": "InclusiveLab #1",
            "categoria": "Diseño",
            "descripcion": "Puesto de Desarrollador Backend accesible para personas con discapacidad Intelectual.",
            "ciudad": "Lima",
            "modalidad": "Híbrido",
            "discapacidad": "Intelectual",
            "estado": "Activa",
            "fecha": "2025-08-06"
        },
        {
            "id": 20,
            "titulo": "Desarrollador Backend",
            "empresa": "Cloudify #2",
            "categoria": "Tecnología",
            "descripcion": "Puesto de Desarrollador Backend accesible para personas con discapacidad Intelectual.",
            "ciudad": "Piura",
            "modalidad": "Presencial",
            "discapacidad": "Intelectual",
            "estado": "Activa",
            "fecha": "2025-03-06"
        }
    ],
    "mensajes": [],
    "postulaciones": []
};
    if (!localStorage.getItem("TI_DATABASE")) {
        localStorage.setItem("TI_DATABASE", JSON.stringify(data));
        console.log(" Base de datos inicial cargada en localStorage (TI_DATABASE)");
    } else {
        console.log("ℹ TI_DATABASE ya existía en localStorage, no se sobrescribió.");
    }
})();
